= OpenZeppelin Truffle Upgrades API

Both `deployProxy` and `upgradeProxy` functions will return instances of https://www.trufflesuite.com/docs/truffle/reference/contract-abstractions[Truffle contracts], and require Truffle contract classes (retrieved via `artifacts.require`) as arguments.

[[common-options]]
== Common Options

The following options are common to all functions.

* `deployer`: Should be set to the Truffle migration deployer during migrations.
* `kind`: (`"uups" | "transparent"`) Choose between a UUPS or Transparent proxy. Defaults to Transparent. See xref:contracts:api:proxy.adoc#transparent-vs-uups[Transparent vs UUPS].
* `unsafeAllow`: (`ValidationError[]`) Selectively disable one or more validation errors:
** `"external-library-linking"`: Allows a deployment with external libraries linked to the implementation contract. (External libraries are otherwise xref:faq.adoc#why-cant-i-use-external-libraries[not yet supported].)
** `"struct-definition"`, `"enum-definition"`: Used to be necessary to deploy a contract with structs or enums. No longer necessary.
** `"state-variable-assignment"`: Allows assigning state variables in a contract even though they will be stored in the implementation.
** `"state-variable-immutable"`: Allows use of immutable variables, which are not unsafe
** `"constructor"`: Allows defining a constructor. Note that constructor arguments are not supported regardless of this option.
** `"delegatecall"`, `"selfdestruct"`: Allow the use of these operations. Incorrect use of this option can put funds at risk of permanent loss. See xref:faq.adoc#delegatecall-selfdestruct[Can I safely use `delegatecall` and `selfdestruct`?]
** `"missing-public-upgradeto"`: Allow UUPS implementations that do not contain a public `upgradeTo` function. Enabling this option is likely to cause a revert due to the built-in UUPS safety mechanism.
* `unsafeAllowRenames`: (`boolean`) Configure storage layout check to allow variable renaming.

Note that the options un `unsafeAllow` can also be specified in a more granular way directly in the source code if using Solidity >=0.8.2. See xref:faq.adoc#how-can-i-disable-checks[How can I disable some of the checks?]

The following options have been deprecated.

* `unsafeAllowLinkedLibraries`: Equivalent to including `"external-library-linking"` in `unsafeAllow`.
* `unsafeAllowCustomTypes`: Equivalent to including `"struct-definition"` and `"enum-definition"` in `unsafeAllow`. No longer necessary.

[[deploy-proxy]]
== deployProxy

Creates a proxy given a Truffle contract class to use as implementation, and returns a contract instance with the proxy address and the implementation interface. During a migration, the proxy address will be stored in the implementation contract's artifact, so you can use Truffle's https://www.trufflesuite.com/docs/truffle/reference/contract-abstractions#-code-mycontract-deployed-code-[`deployed()`] function to load it.

If `args` is set, will call an initializer function `initialize` with the supplied `args` during proxy deployment.

* `initializer`: set a different initializer function to call, or specify `false` to disable initialization
* See <<common-options>>.

[source,ts]
----
async function deployProxy(
  Contract: ContractClass,
  args: unknown[] = [],
  opts: {
    deployer: Deployer,
    initializer: string | false,
    unsafeAllow: ValidationError[],
    kind: 'uups' | 'transparent',
  } = {},
): Promise<ContractInstance>
----

[[upgrade-proxy]]
== upgradeProxy

Upgrades a proxy at a specified address to a new implementation contract, and returns a contract instance with the proxy address and the new implementation interface.

See <<common-options>>.

[source,ts]
----
async function upgradeProxy(
  proxyAddress: string,
  Contract: ContractClass,
  opts: {
    deployer: Deployer,
    unsafeAllow: ValidationError[],
  } = {},
): Promise<ContractInstance>
----

[[prepare-upgrade]]
== prepareUpgrade

Validates and deploys a new implementation contract, and returns its address. Use this method to prepare an upgrade to be run from an admin address you do not control directly or cannot use from Truffle.

See <<common-options>>.

[source,ts]
----
async function prepareUpgrade(
  proxyAddress: string,
  Contract: ContractClass,
  opts: {
    deployer: Deployer,
    unsafeAllow: ValidationError[],
  } = {},
): Promise<string>
----

[[admin-change-admin-for-proxy]]
== admin.changeAdminForProxy

Changes the admin for a specific proxy. Receives the address of the proxy to change, and the new admin address.

[source,ts]
----
async function changeAdminForProxy(
  proxyAddress: string,
  newAdmin: string,
): Promise<void>
----

[[admin-transfer-proxy-admin-ownership]]
== admin.transferProxyAdminOwnership

Changes the owner of the proxy admin contract, which is the default admin for upgrade rights over all proxies. Receives the new admin address.

[source,ts]
----
async function transferProxyAdminOwnership(
  newAdmin: string,
): Promise<void>
----

== silenceWarnings

Silences all subsequent warnings about the use of unsafe flags. Prints a last warning before doing so.

NOTE: This function is useful for tests, but its use in production deployment scripts is discouraged.

[source,ts]
----
function silenceWarnings()
----
