= OpenZeppelin Hardhat Upgrades API

Both `deployProxy` and `upgradeProxy` functions will return instances of https://docs.ethers.io/v5/api/contract/contract[ethers.js contracts], and require https://docs.ethers.io/v5/api/contract/contract-factory[ethers.js contract factories] as arguments. For https://docs.openzeppelin.com/contracts/4.x/api/proxy#beacon[beacons], `deployBeacon` and `upgradeBeacon` will both return an upgradable beacon instance that can be used with a beacon proxy. All functions validate that the implementation contract is upgrade-safe, and will fail otherwise.

[[common-options]]
== Common Options

The following options are common to all functions.

* `kind`: (`"uups" | "transparent"`) Choose between a UUPS or Transparent proxy. Defaults to Transparent. See xref:contracts:api:proxy.adoc#transparent-vs-uups[Transparent vs UUPS]. Not applicable for Beacon proxies.
* `unsafeAllow`: (`ValidationError[]`) Selectively disable one or more validation errors:
** `"external-library-linking"`: Allows a deployment with external libraries linked to the implementation contract. (External libraries are otherwise xref:faq.adoc#why-cant-i-use-external-libraries[not yet supported].)
** `"struct-definition"`, `"enum-definition"`: Used to be necessary to deploy a contract with structs or enums. No longer necessary.
** `"state-variable-assignment"`: Allows assigning state variables in a contract even though they will be stored in the implementation.
** `"state-variable-immutable"`: Allows use of immutable variables, which are not unsafe
** `"constructor"`: Allows defining a constructor. Note that constructor arguments are not supported regardless of this option.
** `"delegatecall"`, `"selfdestruct"`: Allow the use of these operations. Incorrect use of this option can put funds at risk of permanent loss. See xref:faq.adoc#delegatecall-selfdestruct[Can I safely use `delegatecall` and `selfdestruct`?]
** `"missing-public-upgradeto"`: Allow UUPS implementations that do not contain a public `upgradeTo` function. Enabling this option is likely to cause a revert due to the built-in UUPS safety mechanism.
* `unsafeAllowRenames`: (`boolean`) Configure storage layout check to allow variable renaming.
* `constructorArgs`: (`unknown[]`) Provide arguments for the constructor of the implementation contract. Note that these are different from initializer arguments, and will be used in the deployment of the implementation contract itself. Can be used to initialize immutable variables.
* `timeout`: (`number`) Timeout in milliseconds to wait for the transaction confirmation when deploying an implementation contract or proxy admin contract. Defaults to `60000`. Use `0` to wait indefinitely. 
* `pollingInterval`: (`number`) Polling interval in milliseconds between checks for the transaction confirmation when deploying an implementation contract or proxy admin contract. Defaults to `5000`.

Note that the options `unsafeAllow` can also be specified in a more granular way directly in the source code if using Solidity >=0.8.2. See xref:faq.adoc#how-can-i-disable-checks[How can I disable some of the checks?]

The following options have been deprecated.

* `unsafeAllowLinkedLibraries`: Equivalent to including `"external-library-linking"` in `unsafeAllow`.
* `unsafeAllowCustomTypes`: Equivalent to including `"struct-definition"` and `"enum-definition"` in `unsafeAllow`. No longer necessary.

[[deploy-proxy]]
== deployProxy

Creates a UUPS or Transparent proxy given an ethers contract factory to use as implementation, and returns a contract instance with the proxy address and the implementation interface. If `args` is set, will call an initializer function `initialize` with the supplied args during proxy deployment.

If you call `deployProxy` several times for the same implementation contract, several proxies will be deployed, but only one implementation contract will be used.

* `initializer`: set a different initializer function to call (see link:++https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--specifying-fragments++[Specifying Fragments]), or specify `false` to disable initialization
* See <<common-options>>.

[source,ts]
----
async function deployProxy(
  Contract: ethers.ContractFactory,
  args: unknown[] = [],
  opts: {
    initializer: string | false,
    unsafeAllow: ValidationError[],
    kind: 'uups' | 'transparent',
  } = {},
): Promise<ethers.Contract>
----

[[upgrade-proxy]]
== upgradeProxy

Upgrades a UUPS or Transparent proxy at a specified address to a new implementation contract, and returns a contract instance with the proxy address and the new implementation interface.

* `call`: enables the execution of an arbitrary function call during the upgrade process. This call is described using a function name, signature, or selector (see https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--specifying-fragments[Specifying Fragments]), and optional arguments. It is batched into the upgrade transaction, making it safe to call migration initializing functions.
* See <<common-options>>.

[source,ts]
----
async function upgradeProxy(
  proxyAddress: string,
  Contract: ethers.ContractFactory,
  opts: {
    call: string | { fn: string; args?: unknown[] },
    unsafeAllow: ValidationError[],
  } = {},
): Promise<ethers.Contract>
----

[[deploy-beacon]]
== deployBeacon

Creates an https://docs.openzeppelin.com/contracts/4.x/api/proxy#UpgradeableBeacon[upgradable beacon] given an ethers contract factory to use as implementation, and returns the beacon contract instance.

* See <<common-options>>.

[source,ts]
----
async function deployBeacon(
  Contract: ethers.ContractFactory,
  opts: {
    unsafeAllow: ValidationError[],
  } = {},
): Promise<ethers.Contract>
----

[[upgrade-beacon]]
== upgradeBeacon

Upgrades an https://docs.openzeppelin.com/contracts/4.x/api/proxy#UpgradeableBeacon[upgradable beacon] at a specified address to a new implementation contract, and returns the beacon contract instance.

* See <<common-options>>.

[source,ts]
----
async function upgradeBeacon(
  beaconAddress: string,
  Contract: ethers.ContractFactory,
  opts: {
    unsafeAllow: ValidationError[],
  } = {},
): Promise<ethers.Contract>
----

[[deploy-beacon-proxy]]
== deployBeaconProxy

Creates a https://docs.openzeppelin.com/contracts/4.x/api/proxy#BeaconProxy[Beacon proxy] given an existing beacon contract address and an ethers contract factory corresponding to the beacon's current implementation contract, and returns a contract instance with the beacon proxy address and the implementation interface. If `args` is set, will call an initializer function `initialize` with the supplied args during proxy deployment.

* `initializer`: set a different initializer function to call (see https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--specifying-fragments[Specifying Fragments]), or specify `false` to disable initialization

[source,ts]
----
async function deployBeaconProxy(
  beaconAddress: string,
  attachTo: ethers.ContractFactory,
  args: unknown[] = [],
  opts: {
    initializer?: string | false,
  } = {},
): Promise<ethers.Contract>
----

[[force-import]]
== forceImport

Forces the import of an existing proxy or beacon deployment to be used with this plugin. Provide the address of an existing proxy or beacon and the ethers contract factory of the implementation contract that was deployed. Use this function to recreate a lost https://docs.openzeppelin.com/upgrades-plugins/1.x/network-files[network file] by importing previous deployments, or to register proxies or beacons for upgrading even if they were not originally deployed by this plugin. Supported for UUPS, Transparent, and Beacon proxies, as well as beacons.

* See <<common-options>>.

[source,ts]
----
async function forceImport(
  proxyOrBeaconAddress: string,
  deployedImpl: ethers.ContractFactory,
  opts: {} = {},
): Promise<ethers.Contract>
----

[[prepare-upgrade]]
== prepareUpgrade

Validates and deploys a new implementation contract, and returns its address. Use this method to prepare an upgrade to be run from an admin address you do not control directly or cannot use from Hardhat. Supported for UUPS, Transparent, and Beacon proxies, as well as beacons.

See <<common-options>>.

[source,ts]
----
async function prepareUpgrade(
  proxyOrBeaconAddress: string,
  Contract: ethers.ContractFactory,
  opts: {
    unsafeAllow: ValidationError[],
  } = {},
): Promise<string>
----

[[defender-propose-upgrade]]
== defender.proposeUpgrade

NOTE: This method requires the https://www.npmjs.com/package/@openzeppelin/hardhat-defender[`@openzeppelin/hardhat-defender`] package, as well as configuring a Defender Team API Key.

Similar to `prepareUpgrade`. This method validates and deploys the new implementation contract, but also creates an upgrade proposal in https://docs.openzeppelin.com/defender/admin[Defender Admin], for review and approval by the upgrade administrators. Supported for UUPS or Transparent proxies. Not currently supported for beacon proxies or beacons. For beacons, use `prepareUpgrade` along with a custom action in Defender Admin to upgrade the beacon to the deployed implementation.

* `title`: title of the upgrade proposal as seen in Defender Admin, defaults to `Upgrade to 0x12345678` (using the first 8 digits of the new implementation address)
* `description`: description of the upgrade proposal as seen in Defender Admin, defaults to the full implementation address.
* `multisig`: address of the multisignature wallet contract with the rights to execute the upgrade. This is autodetected in https://docs.openzeppelin.com/contracts/4.x/api/proxy#TransparentUpgradeableProxy[Transparent proxies], but required for https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable[UUPS proxies] (read more https://docs.openzeppelin.com/contracts/4.x/api/proxy#transparent-vs-uups[here]). Both Gnosis Safe and Gnosis MultisigWallet multisigs are supported.
* `proxyAdmin`: address of the https://docs.openzeppelin.com/contracts/4.x/api/proxy#ProxyAdmin[`ProxyAdmin`] contract that manages the proxy, if exists. This is autodetected in https://docs.openzeppelin.com/contracts/4.x/api/proxy#TransparentUpgradeableProxy[Transparent proxies], but required for https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable[UUPS proxies] (read more https://docs.openzeppelin.com/contracts/4.x/api/proxy#transparent-vs-uups[here]), though UUPS proxies typically do not require the usage of a ProxyAdmin.

* See <<common-options>>.

[source,ts]
----
async function proposeUpgrade(
  proxyAddress: string,
  ImplFactory: ContractFactory,
  opts: {
    unsafeAllow?: ValidationError[],
    title?: string,
    description?: string,
    multisig?: string,
    proxyAdmin?: string,
  } = {},
): Promise<void>
----

[[admin-change-proxy-admin]]
== admin.changeProxyAdmin

Changes the admin for a specific proxy. Receives the address of the proxy to change, and the new admin address.

[source,ts]
----
async function changeProxyAdmin(
  proxyAddress: string,
  newAdmin: string,
): Promise<void>
----

[[admin-transfer-proxy-admin-ownership]]
== admin.transferProxyAdminOwnership

Changes the owner of the proxy admin contract, which is the default admin for upgrade rights over all proxies. Receives the new admin address.

[source,ts]
----
async function transferProxyAdminOwnership(
  newAdmin: string,
): Promise<void>
----

[[erc1967]]
== erc1967

Functions in this module provide access to the https://eips.ethereum.org/EIPS/eip-1967[ERC1967] variables of a proxy contract.

[source,ts]
----
async function erc1967.getImplementationAddress(proxyAddress: string): Promise<string>;
async function erc1967.getBeaconAddress(proxyAddress: string): Promise<string>;
async function erc1967.getAdminAddress(proxyAddress: string): Promise<string>;
----

[[beacon]]
== beacon

This module provides a convenience function to get the implementation address from a beacon contract.

[source,ts]
----
async function beacon.getImplementationAddress(beaconAddress: string): Promise<string>;
----

== silenceWarnings

Silences all subsequent warnings about the use of unsafe flags. Prints a last warning before doing so.

NOTE: This function is useful for tests, but its use in production deployment scripts is discouraged.

[source,ts]
----
function silenceWarnings()
----
