= OpenZeppelin Hardhat Upgrades API

Both `deployProxy` and `upgradeProxy` functions will return instances of https://docs.ethers.io/v5/api/contract/contract[ethers.js contracts], and require https://docs.ethers.io/v5/api/contract/contract-factory[ethers.js contract factories] as arguments. All functions validate that the implementation contract is upgrade-safe, and will fail otherwise.

[[deploy-proxy]]
== deployProxy

Creates a proxy given an ethers contract factory to use as implementation, and returns a contract instance with the proxy address and the implementation interface. If `args` is set, will call an initializer function `initialize` with the supplied args during proxy deployment.

Options are:

* `initializer`: set a different initializer function to call, or specify `false` to disable initialization
* `unsafeAllowLinkedLibraries`: allows a deployment with external libraries linked to the implementation contract (required since the plugins do not support xref:faq.adoc#why-cant-i-use-external-libraries[external libraries] yet)
* `unsafeAllowCustomTypes`: an override for a few situations where structs or enums cannot be automatically verified for safety
* `unsafeAllow`: selectively disable one or multiple errors types.

[source,ts]
----
async function deployProxy(
  Contract: ethers.ContractFactory,
  args: unknown[] = [],
  opts: { initializer: string | false, unsafeAllowCustomTypes: boolean, unsafeAllowLinkedLibraries: boolean, unsafeAllow: string[] } = {},
): Promise<ethers.Contract>
----

[[upgrade-proxy]]
== upgradeProxy

Upgrades a proxy at a specified address to a new implementation contract, and returns a contract instance with the proxy address and the new implementation interface.

Options are:

* `unsafeAllowLinkedLibraries`: allows an upgrade with external libraries linked to the implementation contract (required since the plugins do not support xref:faq.adoc#why-cant-i-use-external-libraries[external libraries] yet)
* `unsafeAllowCustomTypes`: an override for a few situations where structs or enums cannot be automatically verified for safety
* `unsafeAllow`: selectively disable one or multiple errors types.

[source,ts]
----
async function upgradeProxy(
  proxyAddress: string,
  Contract: ethers.ContractFactory,
  opts: { unsafeAllowCustomTypes: boolean, unsafeAllowLinkedLibraries: boolean, unsafeAllow: string[] } = {},
): Promise<ethers.Contract>
----

[[prepare-upgrade]]
== prepareUpgrade

Validates and deploys a new implementation contract, and returns its address. Use this method to prepare an upgrade to be run from an admin address you do not control directly or cannot use from Hardhat.

Options are:

* `unsafeAllowLinkedLibraries`: allows an upgrade with external libraries linked to the implementation contract (required since the plugins do not support xref:faq.adoc#why-cant-i-use-external-libraries[external libraries] yet)
* `unsafeAllowCustomTypes`: an override for a few situations where structs or enums cannot be automatically verified for safety
* `unsafeAllow`: selectively disable one or multiple errors types.

[source,ts]
----
async function prepareUpgrade(
  proxyAddress: string,
  Contract: ethers.ContractFactory,
  opts: { unsafeAllowCustomTypes: boolean, unsafeAllowLinkedLibraries: boolean, unsafeAllow: string[] } = {},
): Promise<string>
----

[[defender-propose-upgrade]]
== defender.proposeUpgrade

NOTE: This method requires the https://www.npmjs.com/package/@openzeppelin/hardhat-defender[`@openzeppelin/hardhat-defender`] package, as well as configuring a Defender Team API Key.

Similar to `prepareUpgrade`. This method validates and deploys the new implementation contract, but also creates an upgrade proposal in https://docs.openzeppelin.com/defender/admin[Defender Admin], for review and approval by the upgrade administrators.

Options are:

* `unsafeAllowLinkedLibraries`: allows an upgrade with external libraries linked to the implementation contract (required since the plugins do not support xref:faq.adoc#why-cant-i-use-external-libraries[external libraries] yet)
* `unsafeAllowCustomTypes`: an override for a few situations where structs or enums cannot be automatically verified for safety
* `unsafeAllow`: selectively disable one or multiple errors types.
* `title`: title of the upgrade proposal as seen in Defender Admin, defaults to `Upgrade to 0x12345678` (using the first 8 digits of the new implementation address)
* `description`: description of the upgrade proposal as seen in Defender Admin, defaults to the full implementation address.

[source,ts]
----
async function proposeUpgrade(
  proxyAddress: string,
  ImplFactory: ContractFactory,
  opts: {
    unsafeAllowCustomTypes: boolean, unsafeAllowLinkedLibraries: boolean, unsafeAllow: string[]
    title: string, description: string
  } = {},
): Promise<void>
----

[[admin-change-admin-for-proxy]]
== admin.changeAdminForProxy

Changes the admin for a specific proxy. Receives the address of the proxy to change, and the new admin address.

[source,ts]
----
async function changeAdminForProxy(
  proxyAddress: string,
  newAdmin: string,
): Promise<void>
----

[[admin-transfer-proxy-admin-ownership]]
== admin.transferProxyAdminOwnership

Changes the owner of the proxy admin contract, which is the default admin for upgrade rights over all proxies. Receives the new admin address.

[source,ts]
----
async function transferProxyAdminOwnership(
  newAdmin: string,
): Promise<void>
----

== silenceWarnings

Silences all subsequent warnings about the use of unsafe flags. Prints a last warning before doing so.

NOTE: This function is useful for tests, but its use in production deployment scripts is discouraged.

[source,ts]
----
function silenceWarnings()
----
