= OpenZeppelin Upgrades Core API

The `@openzeppelin/upgrades-core` package provides a command-line interface to check for upgrade safety and storage layout compatibility in upgradeable contracts.  It can be used throughout your development process to ensure that your contracts are upgrade safe and compatible with previous versions.

It also provides lower-level APIs to perform these checks programmatically, and contains the core logic for these checks to be performed with the OpenZeppelin Upgrades plugins.

== Command-Line Interface

Detects upgradeable contracts from a build-info directory and validates whether they are upgrade safe.

[[cli-prerequisites]]
=== Prerequisites

==== Define Upgradeable Contracts

The command-line interface performs upgrade safety checks on contracts that meet any of the following criteria:

- If the contract inherits https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol[`Initializable`].
- If the contract has the `upgradeTo(address)` function. This is true for contracts that inherit https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/UUPSUpgradeable.sol[`UUPSUpgradeable`].
- If the contract has the NatSpec annotation `@custom:oz-upgrades`
- If the contract has the NatSpec annotation `@custom:oz-upgrades-from <reference>` as defined below.

==== Define Reference Contracts

CAUTION: If an implementation contract is meant to be used in an upgrade from a previous version, you *MUST* define a reference contract for storage layout comparisons.  Otherwise, you will not receive errors if there are any storage layout incompatibilities.

Define a reference contract by adding the NatSpec annotation `@custom:oz-upgrades-from <reference>` to your implementation contract, where `<reference>` is the contract name or fully qualified contract name of the reference contract to use for storage layout compatibility checks.

For example:
[source,solidity]
----
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/// @custom:oz-upgrades-from MyContractV1
contract MyContractV2 {
  ...
}
----

Or:
[source,solidity]
----
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/// @custom:oz-upgrades-from contracts/MyContract.sol:MyContractV1
contract MyContractV2 {
  ...
}
----

==== Compile Contracts

Compile your contracts and ensure that your build artifacts are available as JSON files with Solidity compiler inputs and outputs in a build-info directory. The compiler output must include storage layouts. If any previous build artifacts exist, they must be cleaned first to avoid duplicate contract definitions.

Hardhat:
```
npx hardhat clean && npx hardhat compile
```

Foundry:
```
forge clean && forge build --build-info --extra-output storageLayout
```

=== Usage

After performing the prerequisites, run the `npx @openzeppelin/upgrades-core validate` command to validate your contracts:

[source,bash]
----
npx @openzeppelin/upgrades-core validate [<build-info-dir>] [options]

Arguments:
  <build-info-dir>  Optional path to the build-info directory which contains JSON files with Solidity compiler input and output. Defaults to the Hardhat or Foundry build-info directory if running in a Hardhat or Foundry project.

Options:
  --unsafeAllow "<validation errors>"  Comma or space separated list to selectively disable one or more validation errors. Supported values are: state-variable-assignment, state-variable-immutable, external-library-linking, struct-definition, enum-definition, constructor, delegatecall, selfdestruct, missing-public-upgradeto
  --unsafeAllowRenames  Configure storage layout check to allow variable renaming.
  --unsafeSkipStorageCheck  Skips checking for storage layout compatibility errors. This is a dangerous option meant to be used as a last resort.
----

== High-Level API

The package exports a high-level API as a programmatic equivalent to the command-line interface.

=== Pre-requisites

Pre-requisites are the same as for the <<cli-prerequisites, command-line interface>>.

=== Usage

[source,ts]
----
import { validateUpgradeSafety } from '@openzeppelin/upgrades-core';
----

==== validateUpgradeSafety
[source,ts]
----
validateUpgradeSafety(
  buildInfoFilePath?: string,
  reportOpts: ReportOptions = {},
  opts: ValidateUpgradeSafetyOptions = {},
): Promise<SummaryReport>
----

Detects upgradeable contracts from a build-info directory and validates whether they are upgrade safe. Returns a <<summary-report, summary report>> with the results.

*Parameters:*

* `buildInfoFilePath` - the path to the build-info directory which contains JSON files with Solidity compiler input and output. Defaults to the Hardhat or Foundry build-info directory if running in a Hardhat or Foundry project.
* `reportOpts` - an object with the following options:
** `suppressSummary` - whether to skip logging the summary report to the console before returning it.
* `opts` - an object with the following options as defined in xref:api-hardhat-upgrades.adoc#common-options[Common Options]:
** `unsafeAllow`
** `unsafeAllowRenames`
** `unsafeSkipStorageCheck`

*Returns:* a <<summary-report, summary report>>.

[[summary-report]]
==== SummaryReport
[source,ts]
----
interface SummaryReport {
  ok: boolean;
  explain(color?: boolean): string;
  numPassed: number;
  numTotal: number;
}
----

An object that represents the result of the upgrade safety checks and contains a summary of the errors found.

**Members:**

* `ok` - `false` if any errors were found, otherwise `true`.
* `explain()` - returns a message explaining the errors in detail, if any.
* `numPassed` - number of contracts that passed upgrade safety checks.
* `numTotal` - total number of upgradeable contracts detected.

== Low-Level API

The package exports a standalone interface that works with https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description[Solidity input and output JSON objects].

=== Usage

[source,ts]
----
import { UpgradeableContract } from '@openzeppelin/upgrades-core';
----

==== UpgradeableContract

This class represents the implementation for an upgradeable contract and gives access to error reports.

===== constructor UpgradeableContract
[source,ts]
----
constructor UpgradeableContract(
  name: string,
  solcInput: SolcInput,
  solcOutput: SolcOutput,
  opts?: {
    unsafeAllow?: ValidationError[],
    unsafeAllowRenames?: boolean,
    unsafeSkipStorageCheck?: boolean,
    kind?: 'uups' | 'transparent' | 'beacon',
  },
): UpgradeableContract
----

Creates a new instance of `UpgradeableContract`.

*Parameters:*

* `name` - the name of the implementation contract as either a fully qualified name or contract name. If multiple contracts have the same name, you must use the fully qualified name e.g., `contracts/Bar.sol:Bar`.
* `solcInput` - the Solidity input JSON object for the implementation contract.
* `solcOutput` - the Solidity output JSON object for the implementation contract.
* `opts` - an object with options as defined in xref:api-hardhat-upgrades.adoc#common-options[Common Options].

TIP: In Hardhat, `solcInput` and `solcOutput` can be obtained from the Build Info file, which itself can be retrieved with `hre.artifacts.getBuildInfo`.

===== .getErrorReport
[source,ts]
----
getErrorReport(): Report
----

**Returns:**

* a report about errors pertaining to proxied contracts, e.g. the use of `selfdestruct`.

===== .getStorageUpgradeReport
[source,ts]
----
getStorageUpgradeReport(
  upgradedContract: UpgradeableContract,
  opts?: {
    unsafeAllow?: ValidationError[],
    unsafeAllowRenames?: boolean,
    unsafeSkipStorageCheck?: boolean,
    kind?: 'uups' | 'transparent' | 'beacon',
  },
): Report
----

Compares the storage layout of an upgradeable contract with that of a proposed upgrade.

*Parameters:*

* `upgradedContract` - another instance of `UpgradeableContract` representing the proposed upgrade.

* `opts` - an object with the following options as defined in xref:api-hardhat-upgrades.adoc#common-options[Common Options]:
** `kind`
** `unsafeAllow`
** `unsafeAllowRenames`
** `unsafeSkipStorageCheck`

**Returns:**

* a report about errors pertaining to proxied contracts, e.g. the use of `selfdestruct`, and storage layout conflicts.

==== Report
[source,ts]
----
interface Report {
  ok: boolean;
  explain(color?: boolean): string;
}
----

An object that represents the results of an analysis.

**Members:**

* `ok` - `false` if any errors were found, otherwise `true`.
* `explain()` - returns a message explaining the errors in detail, if any.

