= Upgrades Plugins

**Integrate upgrades into your existing workflow.** There are plugins for [Hardhat](https://hardhat.org/) and [Truffle](https://www.trufflesuite.com/truffle), and full suite [Brownie](https://github.com/eth-brownie/brownie) examples to deploy and manage upgradeable contracts on Ethereum.

* Deploy upgradeable contracts.
* Upgrade deployed contracts.
* Manage proxy admin rights.
* Easily use in tests.

TIP: Upgrades Plugins are only a part of a comprehensive set of OpenZeppelin tools for deploying and securing upgradeable smart contracts. xref:openzeppelin::upgrades.adoc[Check out the full list of resources].

== Overview

[[install]]
=== Installation

[[install-hardhat]]
==== Hardhat install

[source,console]
----
$ npm install --save-dev @openzeppelin/hardhat-upgrades @nomiclabs/hardhat-ethers ethers
----

This installs our Hardhat plugin along with the necessary peer dependencies.

[[install-truffle]]
==== Truffle install

[source,console]
----
$ npm install --save-dev @openzeppelin/truffle-upgrades
----

[[mix-brownie]]
==== Brownie Mix

[source,console]
----
$ brownie bake upgrades-mix
$ cd upgrades
----

This will download the [Brownie Upgrades Mix](https://github.com/brownie-mix/upgrades-mix).

[[usage]]
=== Usage

See the documentation for using xref:truffle-upgrades.adoc[Truffle Upgrades], xref:hardhat-upgrades.adoc[Hardhat Upgrades], and xref:brownie-upgrades.adoc[Brownie Upgrades], or take a look at the sample code snippets below.

[[hardhat-usage]]
==== Hardhat usage

Hardhat users will be able to write https://hardhat.org/guides/scripts.html[scripts] that use the plugin to deploy or upgrade a contract, and manage proxy admin rights.

[source,js]
----
const { ethers, upgrades } = require("hardhat");

async function main() {
  // Deploying
  const Box = await ethers.getContractFactory("Box");
  const instance = await upgrades.deployProxy(Box, [42]);
  await instance.deployed();

  // Upgrading
  const BoxV2 = await ethers.getContractFactory("BoxV2");
  const upgraded = await upgrades.upgradeProxy(instance.address, BoxV2);
}

main();
----

[[truffle-usage]]
==== Truffle usage

Truffle users will be able to write https://www.trufflesuite.com/docs/truffle/getting-started/running-migrations[migrations] that use the plugin to deploy or upgrade a contract, or manage proxy admin rights.

[source,js]
----
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

module.exports = async function (deployer) {
  const instance = await deployProxy(Box, [42], { deployer });
  const upgraded = await upgradeProxy(instance.address, BoxV2, { deployer });
}
----

[[brownie-usage]]
==== Brownie usage

Brownie users can't use the javascript plugins, but can use the contracts and easily deploy upgrades. In your contracts folder, you'll want to at least have `ProxyAdmin` contract, and whatever proxy methodology contract that you'd like, for example the `TransparentUpgradeableProxy`, in their own folder.

[sourcebash]
----
├── contracts
│   ├── Box.sol
│   ├── BoxV2.sol
│   └── transparent_proxy
│       ├── ProxyAdmin.sol
│       └── TransparentUpgradeableProxy.sol
----

Then, you can have a brownie script that will deploy the proxy admin, the proxy, and the implementation.

[source,python]
----
#!/usr/bin/python3
from brownie import (
    Box,
    BoxV2
    TransparentUpgradeableProxy,
    ProxyAdmin,
    accounts,
    network,
    Contract,
)
from scripts.helpful_scripts import encode_function_data, upgrade


def main():
    account = accounts[0]
    proxy_admin = ProxyAdmin.deploy({"from": account})
    box = Box.deploy({"from": account})
    box_encoded_initializer_function = encode_function_data()
    proxy = TransparentUpgradeableProxy.deploy(
        box.address,
        proxy_admin.address,
        box_encoded_initializer_function,
        {"from": account, "gas_limit": 1000000},
    )
    proxy_box = Contract.from_abi("Box", proxy.address, Box.abi)

    ## Upgrade
    box_v2 = BoxV2.deploy({"from": account})
    upgrade(account, proxy, box_v2, proxy_admin_contract=proxy_admin)
    proxy_box = Contract.from_abi("BoxV2", proxy.address, BoxV2.abi)
----

In your `helpful_scripts.py` file, you'll have 2 functions:

`encode_function_data` and `upgrade`

[source,python]
----
def upgrade(
    account,
    proxy,
    newimplementation_address,
    proxy_admin_contract=None,
    initializer=None,
    *args
):
    transaction = None
    if proxy_admin_contract:
        if initializer:
            encoded_function_call = encode_function_data(initializer, *args)
            transaction = proxy_admin_contract.upgradeAndCall(
                proxy.address,
                newimplementation_address,
                encoded_function_call,
                {"from": account},
            )
        else:
            transaction = proxy_admin_contract.upgrade(
                proxy.address, newimplementation_address, {"from": account}
            )
    else:
        if initializer:
            encoded_function_call = encode_function_data(initializer, *args)
            transaction = proxy.upgradeToAndCall(
                newimplementation_address, encoded_function_call, {"from": account}
            )
        else:
            transaction = proxy.upgradeTo(newimplementation_address, {"from": account})
    return transaction

def encode_function_data(initializer=None, *args):
    if len(args) == 0 or not initializer:
        return eth_utils.to_bytes(hexstr="0x")
    else:
        return initializer.encode_input(*args)
----


[[test-usage]]
==== Test usage

Whether you're using Hardhat or Truffle, you can use the plugin in your tests to ensure everything works as expected.

[source,js]
----
it('works before and after upgrading', async function () {
  const instance = await upgrades.deployProxy(Box, [42]);
  assert.strictEqual(await instance.retrieve(), 42);
  
  await upgrades.upgradeProxy(instance.address, BoxV2);
  assert.strictEqual(await instance.retrieve(), 42);
});
----

For brownie, take a look at the tests in the [upgrades-mix](https://github.com/brownie-mix/upgrades-mix/tree/main/tests).

[[how-plugins-work]]
== How the plugins work

Both plugins provide two main functions, `deployProxy` and `upgradeProxy`, which take care of managing upgradeable deployments of your contracts. In the case of `deployProxy`, this means:

1. Validate that the implementation is xref:faq.adoc#what-does-it-mean-for-a-contract-to-be-upgrade-safe[upgrade safe].

2. Deploy a xref:faq.adoc#what-is-a-proxy-admin[proxy admin] for your project.

3. Deploy the xref:faq.adoc#what-is-an-implementation-contract[implementation contract].

4. Create and initialize the proxy contract.

And when you call `upgradeProxy`:

1. Validate that the new implementation is xref:faq.adoc#what-does-it-mean-for-a-contract-to-be-upgrade-safe[upgrade safe] and is xref:faq.adoc#what-does-it-mean-for-an-implementation-to-be-compatible[compatible] with the previous one.

2. Check if there is an xref:faq.adoc#what-is-an-implementation-contract[implementation contract] deployed with the same bytecode, and deploy one if not.

3. Upgrade the proxy to use the new implementation contract.

The plugins will keep track of all the implementation contracts you have deployed in an `.openzeppelin` folder in the project root, as well as the proxy admin. You will find one file per network there. It is advised that you commit to source control the files for all networks except the development ones (you may see them as `.openzeppelin/unknown-*.json`).

> Note: the format of the files within the `.openzeppelin` folder is not compatible with those of the xref:cli::index.adoc[OpenZeppelin CLI]. If you want to use the Upgrades Plugins for an existing OpenZeppelin CLI project, you can xref:migrate-from-cli.adoc[migrate using the guide].

[[managing-ownership]]
== Managing ownership

All proxies define an _admin_ address which has the rights to upgrade them. By default, the admin is a xref:faq.adoc#what-is-a-proxy-admin[proxy admin contract] deployed behind the scenes. You can change the admin of a proxy by calling the `admin.changeAdminForProxy` function in the plugin. Keep in mind that the _admin_ of a proxy can only upgrade it, but not interact with the implementation contract. Read xref:proxies.adoc#transparent-proxies-and-function-clashes[Transparent Proxies and Function Clashes] for more info on this restriction.

The proxy admin contract also defines an _owner_ address which has the rights to operate it. By default, this address is the externally owned account used during deployment. You can change the proxy admin owner by calling the `admin.transferProxyAdminOwnership` function in the plugin. Note that changing the proxy admin owner effectively transfers the power to upgrade any proxy in your whole project to the new owner, so use with care.

Once you have transferred the rights to upgrade a proxy to another address, you can still use your local setup to validate and deploy the implementation contract. The plugins include a `prepareUpgrade` function that will validate that the new implementation is upgrade-safe and compatible with the previous one, and deploy it using your local Ethereum account. You can then execute the upgrade itself from the admin address. You can also use the `proposeUpgrade` function to automatically set up the upgrade in https://docs.openzeppelin.com/defender/admin[Defender Admin].

Refer to each plugin documentation for more details on the `admin` functions.
