= Using with Truffle

WARNING: This package is deprecated. The recommended alternative is to use https://hardhat.org/[Hardhat] along with the xref:hardhat-upgrades.adoc[Hardhat Upgrades] plugin.

This package adds functions to your Truffle migrations and tests so you can deploy and upgrade proxies for your contracts.

NOTE: Usage from https://www.trufflesuite.com/docs/truffle/getting-started/writing-external-scripts[Truffle external scripts] is not yet supported.

TIP: Check out the https://forum.openzeppelin.com/t/openzeppelin-truffle-upgrades-step-by-step-tutorial/3579[step by step tutorial], showing from creating, testing and deploying, all the way through to upgrading with Gnosis Safe.

[[install]]
== Installation

[source,console]
----
$ npm install --save-dev @openzeppelin/truffle-upgrades
----

This package requires Truffle https://github.com/trufflesuite/truffle/releases/tag/v5.1.35[version 5.1.35] or greater.

[[migrations-usage]]
== Usage in migrations

[[proxies]]
=== Proxies

To deploy an upgradeable instance of one of your contracts in your migrations, use the `deployProxy` function:

[source,js]
----
// migrations/NN_deploy_upgradeable_box.js
const { deployProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');

module.exports = async function (deployer) {
  const instance = await deployProxy(Box, [42], { deployer });
  console.log('Deployed', instance.address);
};
----

This will automatically check that the `Box` contract is upgrade-safe, set up a proxy admin (if needed), deploy an implementation contract for the `Box` contract (unless there is one already from a previous deployment), create a proxy, and initialize it by calling `initialize(42)`.

Then, in a future migration, you can use the `upgradeProxy` function to upgrade the deployed instance to a new version. The new version can be a different contract (such as `BoxV2`), or you can just modify the existing `Box` contract and recompile it - the plugin will note it changed.

[source,js]
----
// migrations/MM_upgrade_box_contract.js
const { upgradeProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

module.exports = async function (deployer) {
  const existing = await Box.deployed();
  const instance = await upgradeProxy(existing.address, BoxV2, { deployer });
  console.log("Upgraded", instance.address);
};
----

The plugin will take care of comparing `BoxV2` to the previous one to ensure they are compatible for the upgrade, deploy the new `BoxV2` implementation contract (unless there is one already from a previous deployment), and upgrade the existing proxy to the new implementation.

[[beacon-proxies]]
=== Beacon proxies

You can also use this plugin to deploy an upgradable beacon for your contract with the `deployBeacon` function, then deploy one or more beacon proxies that point to it by using the `deployBeaconProxy` function.

[source,js]
----
// migrations/NN_deploy_upgradeable_box.js
const { deployBeacon, deployBeaconProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');

module.exports = async function (deployer) {
  const beacon = await deployBeacon(Box);
  console.log('Beacon deployed', beacon.address);

  const instance = await deployBeaconProxy(beacon, Box, [42], { deployer });
  console.log('Box deployed', instance.address);
};
----

In a future migration, you can use the `erc1967.getBeaconAddress` function to get the beacon address from a deployed beacon proxy instance, then call the `upgradeBeacon` function to upgrade that beacon to a new version. When the beacon is upgraded, all of the beacon proxies that point to it will use the new contract implementation.

[source,js]
----
// migrations/MM_upgrade_box_contract.js
const { erc1967, upgradeBeacon } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

module.exports = async function (deployer) {
  const existing = await Box.deployed();

  const beaconAddress = await erc1967.getBeaconAddress(existing.address);
  await upgradeBeacon(beaconAddress, BoxV2, { deployer });
  console.log("Beacon upgraded", beaconAddress);

  const instance = await BoxV2.at(existing.address);
};
----

[[test-usage]]
== Usage in tests

You can also use the plugin's functions from your Truffle tests, in case you want to add tests for upgrading your contracts (which you should!). The API is the same as in the migrations, only that without a `deployer` parameter.

[[proxies-tests]]
=== Proxies

[source,js]
----
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

describe('upgrades', () => {
  it('works', async () => {
    const box = await deployProxy(Box, [42]);
    const box2 = await upgradeProxy(box.address, BoxV2);

    const value = await box2.value();
    assert.equal(value.toString(), '42');
  });
});
----

[[beacon-proxies-tests]]
=== Beacon proxies

[source,js]
----
const { deployBeacon, deployBeaconProxy, upgradeBeacon } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

describe('upgrades', () => {
  it('works', async () => {
    const beacon = await deployBeacon(Box);
    const box = await deployBeaconProxy(beacon, Box, [42]);

    await upgradeBeacon(beacon, BoxV2);
    const box2 = await BoxV2.at(box.address);

    const value = await box2.value();
    assert.equal(value.toString(), '42');
  });
});
----